[changes]
ignore_conventional_commits = true

[package]
versioned_files = [
    "Cargo.toml",
    { path = "Cargo.lock", dependency = "blog" }
]
changelog = "CHANGELOG.md"
extra_changelog_sections = [
    { name = "New Posts", types = ["new-post"] }
]

[[workflows]]
name = "document-change"

[[workflows.steps]]
type = "CreateChangeFile"

[[workflows]]
name = "prepare-release"

[[workflows.steps]]
type = "Command"
command = "git switch -c release"

[[workflows.steps]]
type = "PrepareRelease"

[[workflows.steps]]
type = "Command"
command = "git commit -m \"chore: prepare release $version\""

[[workflows.steps]]
type = "Command"
command = "git push --force --set-upstream origin release"

[[workflows.steps]]
type = "CreatePullRequest"
base = "master"

[workflows.steps.title]
template = "chore: prepare release $version"

[workflows.steps.body]
template = "Release $version"

[[workflows]]
name = "release"

[[workflows.steps]]
type = "Release"

[github]
owner = "n8mgr"
repo = "blog"
