[changes]
ignore_conventional_commits = true

[package]
versioned_files = [
    "Cargo.toml",
    { path = "Cargo.lock", dependency = "blog" }
]
changelog = "CHANGELOG.md"
extra_changelog_sections = [
    { name = "New Posts", types = ["new-post"] }
]

[[workflows]]
name = "document-change"

[[workflows.steps]]
type = "CreateChangeFile"

[[workflows]]
name = "prepare-release"

[[workflows.steps]]
type = "PrepareRelease"

[[workflows]]
name = "release"

[[workflows.steps]]
type = "Release"

[github]
owner = "n8mgr"
repo = "blog"
